name: navajodi
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  flutter_switch: ^0.3.2
  flutter_svg_provider: ^1.0.7
  smooth_page_indicator: ^1.2.0+3
  readmore: ^3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
